### ISSUE TITLE
Should makeProtocolRetriever use protocols instead "bare protocols"?

### ISSUE THREAD

**Issue by jfparadis** [Agoric/make-importer#31]
Currenlty, makeProtocolRetriever takes a map of "bare protocols".
```js
const protoHandlers = new Map([['file', readFile]]);
```
Should it be using a protocol instead?
```js
const protoHandlers = new Map([['file:', readFile]]);
```
Should it be using a plain object?
```js
const protoHandlers = {'file:': readFile};
```

**Comment by michaelfig** [comment]
Probably a plain object is fine.  I only used a Map because of the possibility of something like: `__proto__://do-something`, but if we don't strip the colons, it makes sense as a record key.
