### ISSUE TITLE
Module code is always strict code, but `eval()` is non-strict

### ISSUE THREAD

**Issue by jfparadis** [Agoric/make-importer#33]
This is probably an issue with `@agoric/evaluate` which we will fix towards the end.

**Steps to reproduce**
In `make-importer`, replace `moddir/index.js` with:
```js
export const test = eval("with(value) { }");
```

Then execute:
```sh
$ node -r esm test/test-moddir.js 
```
Actual result:
```
$ node  -r esm test/test-moddir.js 
TAP version 13
# moddir index.js
not ok 1 unexpected exception
  ---
    operator: notEqual
    expected: |-
      [ReferenceError: value is not defined]
    actual: |-
      [ReferenceError: value is not defined]
 ```
Expected result, same as node's native import:
```sh
$ node -r esm test/moddir/index.js
SyntaxError: Strict mode code may not include a with statement
```

**Comment by erights** [comment]
I don't understand. By the time make-importer runs, a sloppy eval should no longer be possible. How does this happen?

**Comment by michaelfig** [comment]
@erights The make-importer tests do not run using Realms or SES or Evaluator, they use the nestable `@agoric/evaluate` module.

@jfparadis It's a consequence of using an outdated 1.x version of `@agoric/evaluate`.  If you use 2.1.3, it enforces strict mode.

**Comment by jfparadis** [comment]
@michaelfig As explained in the pull request,  '@agoric/make-importer` does not use `@agoric/evaluate`.

@erights   '@agoric/make-importer` **currently** uses this mock which is what I was hinting as the source of the problem. 

```js
const evaluate = new Function(`\
with (arguments[1]) {
// console.log('evaluate', arguments[0]);
return eval(arguments[0]);
}`);

```

**Comment by jfparadis** [comment]
Will be resolved with https://github.com/Agoric/make-importer/pull/32
